# docker-compose

version: "3"

services:
  express:
    build:
      context: .
      args:
        - ENV=${npm_package_config_docker_env}
        - VERSION=${npm_package_config_docker_tag}
    image: stevenxie/express-starter:${npm_package_config_docker_tag}
    container_name: express-starter
    ports:
     - "3000:3000"
    volumes:
     - express-vol:/app/dist
    restart: on-failure

volumes:
  express-vol:
